name: Java CI

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: test settings
        run: ./gradlew test jacocoTestReport -x classes -x testClasses
      - name: Upload Test Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test results
          path: build/test-results/junit-platform
